apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19xMG90RWt0RERxc3dBcWhxcC1UQHBhc3MtaW4tZG8tdXNlci0xNjMwODA3OS0wLmMuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL3Bhc3MtaW4/c3NsbW9kZT1yZXF1aXJlCg==